use_frameworks!

platform :ios, '9.0'

target 'WDFCategory_Example' do
  pod 'WDFCategory', :path => '../'

  target 'WDFCategory_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
